name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-latest]
          cabal: ["3.6.2.0"]
          ghc: ["9.2.1"]

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - run: cabal update

    - run: cabal configure --enable-tests --write-ghc-environment-files=always

    - run: cabal freeze

    - uses: actions/cache@v2
      name: cache
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: dependencies
      run: cabal build all --only-dependencies

    - run: cabal build all

    - run: cabal test all
